openapi: 3.0.1
info:
  title: Myrt Desk
  description: Описание доступных методов для работы с API стола.
  version: 1.0.0
servers:
  - url: http://MyrtDesk.local
tags:
  - name: lightstrip
    description: Управление светодионой лентой
  - name: legs
    description: Управление ножками стола
  - name: sensors
    description: Получение данных с сенсоров
paths:
  /lightstrip:
    get:
      tags:
      - lightstrip
      summary: Получить состояние ленты
      responses:
        200:
          description: Текущее состояние ленты
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LightstripState'
  /lightstrip/color:
    put:
      tags:
      - lightstrip
      summary: Задать цвет ленты
      requestBody:
        description: Яркость тоже задаётся здесь, так как является множителем цвета.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LightstripColor'
      responses:
        200:
          description: Успех
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionStatus'
        400:
          description: Не хватает параметров или входной JSON невозможно прочитать
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionStatus'
        500:
          description: Контроллер ленты ответил ошибкой
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionStatus'
  /lightstrip/effects:
    put:
      tags:
      - lightstrip
      summary: Задать активный эффект
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EffectRequest'
      responses:
        200:
          description: Успех
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionStatus'
        400:
          description: Не хватает параметров или входной JSON невозможно прочитать
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionStatus'
        500:
          description: Контроллер ленты ответил ошибкой
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionStatus'
  /lightstrip/power:
    put:
      tags:
      - lightstrip
      summary: Задать состояние питания ленты
      requestBody:
        description: Яркость тоже задаётся здесь, так как является множителем цвета.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LightstripPower'
      responses:
        200:
          description: Успех
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionStatus'
        400:
          description: Не хватает параметров или входной JSON невозможно прочитать
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionStatus'
        500:
          description: Контроллер ленты ответил ошибкой
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionStatus'
  /legs:
    get:
      tags:
      - legs
      summary: Получить высоту ножек
      responses:
        200:
          description: Текущая высота ножек
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Height'
    put:
      tags:
      - legs
      summary: Задать высоту ножек
      requestBody:
        description: Высота задаётся в миллиметрах.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Height'
      responses:
        200:
          description: Успех
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionStatus'
        400:
          description: Не хватает параметров или входной JSON невозможно прочитать
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionStatus'
  /legs/calibrate:
    post:
      tags:
      - legs
      summary: Запустить калибровку ножек
      responses:
        200:
          description: Процедура запущена. Выполнение занимает до 20 секунд
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionStatus'
  /sensors/illuminance:
    get:
      tags:
      - sensors
      summary: Получить данные с датчика освещения
      responses:
        200:
          description: Текущий уровень освещённости стола в люксах
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IlluminanceState'
  /describe:
    get:
      tags:
      - sensors
      summary: Получить информацию об устройстве
      responses:
        200:
          description: Информация об устройстве
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceInformation'


components:
  schemas:
    EffectRequest:
      type: object
      properties:
        active:
          type: integer
          format: int32
    IlluminanceState:
      type: object
      properties:
        value:
          type: integer
          format: int32
          minimum: 0
          maximum: 1000
    DeviceInformation:
      type: object
      properties:
        mac:
          type: string
          example: AA:BB:CC:DD:EE:FF
        rssi:
          type: integer
          format: int32
          minimum: -100
          maximum: 0
          example: -45
        id:
          type: string
          example: "d38ddd"
    Height:
      type: object
      properties:
        height:
          type: integer
          format: int32
          minimum: 650
          maximum: 1250
    LightstripPower:
      type: object
      properties:
        enabled:
          type: boolean
    LightstripColor:
      type: object
      properties:
        brightness:
          type: integer
          format: int32
          minimum: 0
          maximum: 255
        color:
          type: array
          items:
            type: integer
            format: int32
            minimum: 0
            maximum: 255
          minItems: 3
          maxItems: 3
    LightstripState:
      type: object
      properties:
        brightness:
          type: integer
          format: int32
          minimum: 0
          maximum: 255
        color:
          type: array
          items:
            type: integer
            format: int32
            minimum: 0
            maximum: 255
          minItems: 3
          maxItems: 3
        enabled:
          type: boolean
    ActionStatus:
      type: object
      properties:
        status:
          type: string
      xml:
        name: Category
