#pragma once

#define PIN_USONIC_TRIGGER D6
#define PIN_USONIC_ECHO D7
#define PIN_BUTTON D5
#define PIN_OEM_UP D2
#define PIN_OEM_DOWN D1
#define PIN_LIGHTSTRIP_RESET D0
#define PIN_PHOTORESISTOR A0
